#############################################################################
# Makefile for building: babel
# Generated by qmake (2.01a) (Qt 4.8.7) on: sam. oct. 31 14:33:42 2015
# Project:  babel.pro
# Template: subdirs
# Command: /usr/local/bin/qmake -o Makefile babel.pro
#############################################################################

first: make_default
MAKEFILE      = Makefile
QMAKE         = /usr/local/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = $(COPY_FILE)
INSTALL_PROGRAM = $(COPY_FILE)
INSTALL_DIR   = $(COPY_DIR)
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
SUBTARGETS    =  \
		sub-gui \
		sub-app

gui/$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) gui/ || $(MKDIR) gui/ 
	cd gui/ && $(QMAKE) /Users/sergeheitzler/Documents/Serge/Work/Git-Repositories/cpp_babel/gui/gui.pro -o $(MAKEFILE)
sub-gui-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) gui/ || $(MKDIR) gui/ 
	cd gui/ && $(QMAKE) /Users/sergeheitzler/Documents/Serge/Work/Git-Repositories/cpp_babel/gui/gui.pro -o $(MAKEFILE)
sub-gui: gui/$(MAKEFILE) FORCE
	cd gui/ && $(MAKE) -f $(MAKEFILE)
sub-gui-make_default-ordered: gui/$(MAKEFILE) FORCE
	cd gui/ && $(MAKE) -f $(MAKEFILE) 
sub-gui-make_default: gui/$(MAKEFILE) FORCE
	cd gui/ && $(MAKE) -f $(MAKEFILE) 
sub-gui-make_first-ordered: gui/$(MAKEFILE) FORCE
	cd gui/ && $(MAKE) -f $(MAKEFILE) first
sub-gui-make_first: gui/$(MAKEFILE) FORCE
	cd gui/ && $(MAKE) -f $(MAKEFILE) first
sub-gui-all-ordered: gui/$(MAKEFILE) FORCE
	cd gui/ && $(MAKE) -f $(MAKEFILE) all
sub-gui-all: gui/$(MAKEFILE) FORCE
	cd gui/ && $(MAKE) -f $(MAKEFILE) all
sub-gui-clean-ordered: gui/$(MAKEFILE) FORCE
	cd gui/ && $(MAKE) -f $(MAKEFILE) clean
sub-gui-clean: gui/$(MAKEFILE) FORCE
	cd gui/ && $(MAKE) -f $(MAKEFILE) clean
sub-gui-distclean-ordered: gui/$(MAKEFILE) FORCE
	cd gui/ && $(MAKE) -f $(MAKEFILE) distclean
sub-gui-distclean: gui/$(MAKEFILE) FORCE
	cd gui/ && $(MAKE) -f $(MAKEFILE) distclean
sub-gui-install_subtargets-ordered: gui/$(MAKEFILE) FORCE
	cd gui/ && $(MAKE) -f $(MAKEFILE) install
sub-gui-install_subtargets: gui/$(MAKEFILE) FORCE
	cd gui/ && $(MAKE) -f $(MAKEFILE) install
sub-gui-uninstall_subtargets-ordered: gui/$(MAKEFILE) FORCE
	cd gui/ && $(MAKE) -f $(MAKEFILE) uninstall
sub-gui-uninstall_subtargets: gui/$(MAKEFILE) FORCE
	cd gui/ && $(MAKE) -f $(MAKEFILE) uninstall
app/$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) app/ || $(MKDIR) app/ 
	cd app/ && $(QMAKE) /Users/sergeheitzler/Documents/Serge/Work/Git-Repositories/cpp_babel/app/app.pro -o $(MAKEFILE)
sub-app-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) app/ || $(MKDIR) app/ 
	cd app/ && $(QMAKE) /Users/sergeheitzler/Documents/Serge/Work/Git-Repositories/cpp_babel/app/app.pro -o $(MAKEFILE)
sub-app: app/$(MAKEFILE) sub-gui FORCE
	cd app/ && $(MAKE) -f $(MAKEFILE)
sub-app-make_default-ordered: app/$(MAKEFILE) sub-gui-make_default-ordered  FORCE
	cd app/ && $(MAKE) -f $(MAKEFILE) 
sub-app-make_default: app/$(MAKEFILE) sub-gui-make_default FORCE
	cd app/ && $(MAKE) -f $(MAKEFILE) 
sub-app-make_first-ordered: app/$(MAKEFILE) sub-gui-make_first-ordered  FORCE
	cd app/ && $(MAKE) -f $(MAKEFILE) first
sub-app-make_first: app/$(MAKEFILE) sub-gui-make_first FORCE
	cd app/ && $(MAKE) -f $(MAKEFILE) first
sub-app-all-ordered: app/$(MAKEFILE) sub-gui-all-ordered  FORCE
	cd app/ && $(MAKE) -f $(MAKEFILE) all
sub-app-all: app/$(MAKEFILE) sub-gui-all FORCE
	cd app/ && $(MAKE) -f $(MAKEFILE) all
sub-app-clean-ordered: app/$(MAKEFILE) sub-gui-clean-ordered  FORCE
	cd app/ && $(MAKE) -f $(MAKEFILE) clean
sub-app-clean: app/$(MAKEFILE) sub-gui-clean FORCE
	cd app/ && $(MAKE) -f $(MAKEFILE) clean
sub-app-distclean-ordered: app/$(MAKEFILE) sub-gui-distclean-ordered  FORCE
	cd app/ && $(MAKE) -f $(MAKEFILE) distclean
sub-app-distclean: app/$(MAKEFILE) sub-gui-distclean FORCE
	cd app/ && $(MAKE) -f $(MAKEFILE) distclean
sub-app-install_subtargets-ordered: app/$(MAKEFILE) sub-gui-install_subtargets-ordered  FORCE
	cd app/ && $(MAKE) -f $(MAKEFILE) install
sub-app-install_subtargets: app/$(MAKEFILE) sub-gui-install_subtargets FORCE
	cd app/ && $(MAKE) -f $(MAKEFILE) install
sub-app-uninstall_subtargets-ordered: app/$(MAKEFILE) sub-gui-uninstall_subtargets-ordered  FORCE
	cd app/ && $(MAKE) -f $(MAKEFILE) uninstall
sub-app-uninstall_subtargets: app/$(MAKEFILE) sub-gui-uninstall_subtargets FORCE
	cd app/ && $(MAKE) -f $(MAKEFILE) uninstall

Makefile: babel.pro  /usr/local/Cellar/qt/4.8.7_1/mkspecs/unsupported/macx-clang-libc++/qmake.conf /usr/local/Cellar/qt/4.8.7_1/mkspecs/common/unix.conf \
		/usr/local/Cellar/qt/4.8.7_1/mkspecs/common/mac.conf \
		/usr/local/Cellar/qt/4.8.7_1/mkspecs/common/gcc-base.conf \
		/usr/local/Cellar/qt/4.8.7_1/mkspecs/common/gcc-base-macx.conf \
		/usr/local/Cellar/qt/4.8.7_1/mkspecs/common/clang.conf \
		/usr/local/Cellar/qt/4.8.7_1/mkspecs/qconfig.pri \
		/usr/local/Cellar/qt/4.8.7_1/mkspecs/modules/qt_webkit_version.pri \
		/usr/local/Cellar/qt/4.8.7_1/mkspecs/features/qt_functions.prf \
		/usr/local/Cellar/qt/4.8.7_1/mkspecs/features/qt_config.prf \
		/usr/local/Cellar/qt/4.8.7_1/mkspecs/features/exclusive_builds.prf \
		/usr/local/Cellar/qt/4.8.7_1/mkspecs/features/default_pre.prf \
		/usr/local/Cellar/qt/4.8.7_1/mkspecs/features/mac/default_pre.prf \
		/usr/local/Cellar/qt/4.8.7_1/mkspecs/features/release.prf \
		/usr/local/Cellar/qt/4.8.7_1/mkspecs/features/default_post.prf \
		/usr/local/Cellar/qt/4.8.7_1/mkspecs/features/mac/default_post.prf \
		/usr/local/Cellar/qt/4.8.7_1/mkspecs/features/mac/x86_64.prf \
		/usr/local/Cellar/qt/4.8.7_1/mkspecs/features/mac/objective_c.prf \
		/usr/local/Cellar/qt/4.8.7_1/mkspecs/features/shared.prf \
		/usr/local/Cellar/qt/4.8.7_1/mkspecs/features/warn_on.prf \
		/usr/local/Cellar/qt/4.8.7_1/mkspecs/features/qt.prf \
		/usr/local/Cellar/qt/4.8.7_1/mkspecs/features/unix/thread.prf \
		/usr/local/Cellar/qt/4.8.7_1/mkspecs/features/moc.prf \
		/usr/local/Cellar/qt/4.8.7_1/mkspecs/features/mac/rez.prf \
		/usr/local/Cellar/qt/4.8.7_1/mkspecs/features/mac/sdk.prf \
		/usr/local/Cellar/qt/4.8.7_1/mkspecs/features/resources.prf \
		/usr/local/Cellar/qt/4.8.7_1/mkspecs/features/uic.prf \
		/usr/local/Cellar/qt/4.8.7_1/mkspecs/features/yacc.prf \
		/usr/local/Cellar/qt/4.8.7_1/mkspecs/features/lex.prf \
		/usr/local/Cellar/qt/4.8.7_1/mkspecs/features/include_source_dir.prf
	$(QMAKE) -o Makefile babel.pro
/usr/local/Cellar/qt/4.8.7_1/mkspecs/common/unix.conf:
/usr/local/Cellar/qt/4.8.7_1/mkspecs/common/mac.conf:
/usr/local/Cellar/qt/4.8.7_1/mkspecs/common/gcc-base.conf:
/usr/local/Cellar/qt/4.8.7_1/mkspecs/common/gcc-base-macx.conf:
/usr/local/Cellar/qt/4.8.7_1/mkspecs/common/clang.conf:
/usr/local/Cellar/qt/4.8.7_1/mkspecs/qconfig.pri:
/usr/local/Cellar/qt/4.8.7_1/mkspecs/modules/qt_webkit_version.pri:
/usr/local/Cellar/qt/4.8.7_1/mkspecs/features/qt_functions.prf:
/usr/local/Cellar/qt/4.8.7_1/mkspecs/features/qt_config.prf:
/usr/local/Cellar/qt/4.8.7_1/mkspecs/features/exclusive_builds.prf:
/usr/local/Cellar/qt/4.8.7_1/mkspecs/features/default_pre.prf:
/usr/local/Cellar/qt/4.8.7_1/mkspecs/features/mac/default_pre.prf:
/usr/local/Cellar/qt/4.8.7_1/mkspecs/features/release.prf:
/usr/local/Cellar/qt/4.8.7_1/mkspecs/features/default_post.prf:
/usr/local/Cellar/qt/4.8.7_1/mkspecs/features/mac/default_post.prf:
/usr/local/Cellar/qt/4.8.7_1/mkspecs/features/mac/x86_64.prf:
/usr/local/Cellar/qt/4.8.7_1/mkspecs/features/mac/objective_c.prf:
/usr/local/Cellar/qt/4.8.7_1/mkspecs/features/shared.prf:
/usr/local/Cellar/qt/4.8.7_1/mkspecs/features/warn_on.prf:
/usr/local/Cellar/qt/4.8.7_1/mkspecs/features/qt.prf:
/usr/local/Cellar/qt/4.8.7_1/mkspecs/features/unix/thread.prf:
/usr/local/Cellar/qt/4.8.7_1/mkspecs/features/moc.prf:
/usr/local/Cellar/qt/4.8.7_1/mkspecs/features/mac/rez.prf:
/usr/local/Cellar/qt/4.8.7_1/mkspecs/features/mac/sdk.prf:
/usr/local/Cellar/qt/4.8.7_1/mkspecs/features/resources.prf:
/usr/local/Cellar/qt/4.8.7_1/mkspecs/features/uic.prf:
/usr/local/Cellar/qt/4.8.7_1/mkspecs/features/yacc.prf:
/usr/local/Cellar/qt/4.8.7_1/mkspecs/features/lex.prf:
/usr/local/Cellar/qt/4.8.7_1/mkspecs/features/include_source_dir.prf:
qmake: qmake_all FORCE
	@$(QMAKE) -o Makefile babel.pro

qmake_all: sub-gui-qmake_all sub-app-qmake_all FORCE

make_default: sub-gui-make_default-ordered sub-app-make_default-ordered FORCE
make_first: sub-gui-make_first-ordered sub-app-make_first-ordered FORCE
all: sub-gui-all-ordered sub-app-all-ordered FORCE
clean: sub-gui-clean-ordered sub-app-clean-ordered FORCE
distclean: sub-gui-distclean-ordered sub-app-distclean-ordered FORCE
	-$(DEL_FILE) Makefile
install_subtargets: sub-gui-install_subtargets-ordered sub-app-install_subtargets-ordered FORCE
uninstall_subtargets: sub-gui-uninstall_subtargets-ordered sub-app-uninstall_subtargets-ordered FORCE

servermake:
	cd ./server && make re

clean:
	rm -f */*.o rm -f */*/*.o rm -f *~ rm -f */*~ rm -f */*/*~ rm -f */moc_* rm -f */*/moc_*

fclean:
	rm -f */*.o rm -f */*.a rm -f */*/*.o rm -f */*~ rm -f */*/*~ rm -f */moc_* rm -f */*/moc_* rm -f *.o rm -f moc_* rm -f babelUI

re:
	make clean all

sub-gui-check_ordered: gui/$(MAKEFILE)
	cd gui/ && $(MAKE) -f $(MAKEFILE) check
sub-app-check_ordered: app/$(MAKEFILE) sub-gui-check_ordered 
	cd app/ && $(MAKE) -f $(MAKEFILE) check
check: sub-gui-check_ordered sub-app-check_ordered

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all
install: install_subtargets  FORCE

uninstall:  uninstall_subtargets FORCE

FORCE:

