#############################################################################
# Makefile for building: babel
# Generated by qmake (3.0) (Qt 5.2.1)
# Project:  babel.pro
# Template: subdirs
# Command: /usr/lib/x86_64-linux-gnu/qt5/bin/qmake -o Makefile babel.pro
#############################################################################

MAKEFILE      = Makefile

first: make_first
QMAKE         = /usr/lib/x86_64-linux-gnu/qt5/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = $(COPY_DIR)
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
SUBTARGETS    =  \
		sub-core \
		sub-app


sub-core-qmake_all:  FORCE
	@test -d core/ || mkdir -p core/
	cd core/ && $(QMAKE) /home/nicolaschr/rendu/cpp_babel/core/core.pro -o Makefile
	cd core/ && $(MAKE) -f Makefile qmake_all
sub-core: FORCE
	@test -d core/ || mkdir -p core/
	cd core/ && ( test -e Makefile || $(QMAKE) /home/nicolaschr/rendu/cpp_babel/core/core.pro -o Makefile ) && $(MAKE) -f Makefile
sub-core-make_first-ordered: FORCE
	@test -d core/ || mkdir -p core/
	cd core/ && ( test -e Makefile || $(QMAKE) /home/nicolaschr/rendu/cpp_babel/core/core.pro -o Makefile ) && $(MAKE) -f Makefile 
sub-core-make_first: FORCE
	@test -d core/ || mkdir -p core/
	cd core/ && ( test -e Makefile || $(QMAKE) /home/nicolaschr/rendu/cpp_babel/core/core.pro -o Makefile ) && $(MAKE) -f Makefile 
sub-core-all-ordered: FORCE
	@test -d core/ || mkdir -p core/
	cd core/ && ( test -e Makefile || $(QMAKE) /home/nicolaschr/rendu/cpp_babel/core/core.pro -o Makefile ) && $(MAKE) -f Makefile all
sub-core-all: FORCE
	@test -d core/ || mkdir -p core/
	cd core/ && ( test -e Makefile || $(QMAKE) /home/nicolaschr/rendu/cpp_babel/core/core.pro -o Makefile ) && $(MAKE) -f Makefile all
sub-core-clean-ordered: FORCE
	@test -d core/ || mkdir -p core/
	cd core/ && ( test -e Makefile || $(QMAKE) /home/nicolaschr/rendu/cpp_babel/core/core.pro -o Makefile ) && $(MAKE) -f Makefile clean
sub-core-clean: FORCE
	@test -d core/ || mkdir -p core/
	cd core/ && ( test -e Makefile || $(QMAKE) /home/nicolaschr/rendu/cpp_babel/core/core.pro -o Makefile ) && $(MAKE) -f Makefile clean
sub-core-distclean-ordered: FORCE
	@test -d core/ || mkdir -p core/
	cd core/ && ( test -e Makefile || $(QMAKE) /home/nicolaschr/rendu/cpp_babel/core/core.pro -o Makefile ) && $(MAKE) -f Makefile distclean
sub-core-distclean: FORCE
	@test -d core/ || mkdir -p core/
	cd core/ && ( test -e Makefile || $(QMAKE) /home/nicolaschr/rendu/cpp_babel/core/core.pro -o Makefile ) && $(MAKE) -f Makefile distclean
sub-core-install_subtargets-ordered: FORCE
	@test -d core/ || mkdir -p core/
	cd core/ && ( test -e Makefile || $(QMAKE) /home/nicolaschr/rendu/cpp_babel/core/core.pro -o Makefile ) && $(MAKE) -f Makefile install
sub-core-install_subtargets: FORCE
	@test -d core/ || mkdir -p core/
	cd core/ && ( test -e Makefile || $(QMAKE) /home/nicolaschr/rendu/cpp_babel/core/core.pro -o Makefile ) && $(MAKE) -f Makefile install
sub-core-uninstall_subtargets-ordered: FORCE
	@test -d core/ || mkdir -p core/
	cd core/ && ( test -e Makefile || $(QMAKE) /home/nicolaschr/rendu/cpp_babel/core/core.pro -o Makefile ) && $(MAKE) -f Makefile uninstall
sub-core-uninstall_subtargets: FORCE
	@test -d core/ || mkdir -p core/
	cd core/ && ( test -e Makefile || $(QMAKE) /home/nicolaschr/rendu/cpp_babel/core/core.pro -o Makefile ) && $(MAKE) -f Makefile uninstall
sub-app-qmake_all: sub-core-qmake_all FORCE
	@test -d app/ || mkdir -p app/
	cd app/ && $(QMAKE) /home/nicolaschr/rendu/cpp_babel/app/app.pro -o Makefile
	cd app/ && $(MAKE) -f Makefile qmake_all
sub-app: sub-core FORCE
	@test -d app/ || mkdir -p app/
	cd app/ && ( test -e Makefile || $(QMAKE) /home/nicolaschr/rendu/cpp_babel/app/app.pro -o Makefile ) && $(MAKE) -f Makefile
sub-app-make_first-ordered: sub-core-make_first-ordered  FORCE
	@test -d app/ || mkdir -p app/
	cd app/ && ( test -e Makefile || $(QMAKE) /home/nicolaschr/rendu/cpp_babel/app/app.pro -o Makefile ) && $(MAKE) -f Makefile 
sub-app-make_first: sub-core-make_first FORCE
	@test -d app/ || mkdir -p app/
	cd app/ && ( test -e Makefile || $(QMAKE) /home/nicolaschr/rendu/cpp_babel/app/app.pro -o Makefile ) && $(MAKE) -f Makefile 
sub-app-all-ordered: sub-core-all-ordered  FORCE
	@test -d app/ || mkdir -p app/
	cd app/ && ( test -e Makefile || $(QMAKE) /home/nicolaschr/rendu/cpp_babel/app/app.pro -o Makefile ) && $(MAKE) -f Makefile all
sub-app-all: sub-core-all FORCE
	@test -d app/ || mkdir -p app/
	cd app/ && ( test -e Makefile || $(QMAKE) /home/nicolaschr/rendu/cpp_babel/app/app.pro -o Makefile ) && $(MAKE) -f Makefile all
sub-app-clean-ordered: sub-core-clean-ordered  FORCE
	@test -d app/ || mkdir -p app/
	cd app/ && ( test -e Makefile || $(QMAKE) /home/nicolaschr/rendu/cpp_babel/app/app.pro -o Makefile ) && $(MAKE) -f Makefile clean
sub-app-clean: sub-core-clean FORCE
	@test -d app/ || mkdir -p app/
	cd app/ && ( test -e Makefile || $(QMAKE) /home/nicolaschr/rendu/cpp_babel/app/app.pro -o Makefile ) && $(MAKE) -f Makefile clean
sub-app-distclean-ordered: sub-core-distclean-ordered  FORCE
	@test -d app/ || mkdir -p app/
	cd app/ && ( test -e Makefile || $(QMAKE) /home/nicolaschr/rendu/cpp_babel/app/app.pro -o Makefile ) && $(MAKE) -f Makefile distclean
sub-app-distclean: sub-core-distclean FORCE
	@test -d app/ || mkdir -p app/
	cd app/ && ( test -e Makefile || $(QMAKE) /home/nicolaschr/rendu/cpp_babel/app/app.pro -o Makefile ) && $(MAKE) -f Makefile distclean
sub-app-install_subtargets-ordered: sub-core-install_subtargets-ordered  FORCE
	@test -d app/ || mkdir -p app/
	cd app/ && ( test -e Makefile || $(QMAKE) /home/nicolaschr/rendu/cpp_babel/app/app.pro -o Makefile ) && $(MAKE) -f Makefile install
sub-app-install_subtargets: sub-core-install_subtargets FORCE
	@test -d app/ || mkdir -p app/
	cd app/ && ( test -e Makefile || $(QMAKE) /home/nicolaschr/rendu/cpp_babel/app/app.pro -o Makefile ) && $(MAKE) -f Makefile install
sub-app-uninstall_subtargets-ordered: sub-core-uninstall_subtargets-ordered  FORCE
	@test -d app/ || mkdir -p app/
	cd app/ && ( test -e Makefile || $(QMAKE) /home/nicolaschr/rendu/cpp_babel/app/app.pro -o Makefile ) && $(MAKE) -f Makefile uninstall
sub-app-uninstall_subtargets: sub-core-uninstall_subtargets FORCE
	@test -d app/ || mkdir -p app/
	cd app/ && ( test -e Makefile || $(QMAKE) /home/nicolaschr/rendu/cpp_babel/app/app.pro -o Makefile ) && $(MAKE) -f Makefile uninstall

Makefile: babel.pro /usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64/qmake.conf /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/shell-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quick.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		babel.pro
	$(QMAKE) -o Makefile babel.pro
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/shell-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformsupport_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qml.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmltest.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quick.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64/qmake.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf:
babel.pro:
qmake: FORCE
	@$(QMAKE) -o Makefile babel.pro

qmake_all: sub-core-qmake_all sub-app-qmake_all FORCE

make_first: sub-core-make_first-ordered sub-app-make_first-ordered FORCE
all: sub-core-all-ordered sub-app-all-ordered FORCE
clean: sub-core-clean-ordered sub-app-clean-ordered FORCE
distclean: sub-core-distclean-ordered sub-app-distclean-ordered FORCE
	-$(DEL_FILE) Makefile
install_subtargets: sub-core-install_subtargets-ordered sub-app-install_subtargets-ordered FORCE
uninstall_subtargets: sub-core-uninstall_subtargets-ordered sub-app-uninstall_subtargets-ordered FORCE

clean:
	rm -f */*.o rm -f */*/*.o rm -f *~ rm -f */*~ rm -f */*/*~ rm -f */moc_* rm -f */*/moc_*

fclean:
	rm -f */*.o rm -f */*/*.o rm -f */*~ rm -f */*/*~ rm -f */moc_* rm -f */*/moc_* rm -f *.o rm -f moc_* rm -f babelUI rm -f */Makefile

re:
	make clean all

sub-core-check_ordered:
	@test -d core/ || mkdir -p core/
	cd core/ && ( test -e Makefile || $(QMAKE) /home/nicolaschr/rendu/cpp_babel/core/core.pro -o Makefile ) && $(MAKE) -f Makefile check
sub-app-check_ordered: sub-core-check_ordered 
	@test -d app/ || mkdir -p app/
	cd app/ && ( test -e Makefile || $(QMAKE) /home/nicolaschr/rendu/cpp_babel/app/app.pro -o Makefile ) && $(MAKE) -f Makefile check
check: sub-core-check_ordered sub-app-check_ordered
install: install_subtargets  FORCE

uninstall:  uninstall_subtargets FORCE

FORCE:

